### ISSUE TITLE
Installing sqllite3 on windows problem

### ISSUE THREAD

**Issue by ddk632** [ddk632/orange-abacus#3]
- windows 10 known issue with getting sqlite3 to work
- need to fix and document fix
see: https://medium.com/@KarthikPonnam/npm-sqlite3-install-build-error-2ca3374eb004

**Comment by ddk632** [comment]
`npm install --save sqlite3` 
doesn't work: /sqlite3 binary/command-line tool not available

`npm install --build-from-source --save sqlite3`
fails due to v140 MS build tools not available;

>  error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools

The [link](https://landinghub.visualstudio.com/visual-cpp-build-tools) in the Medium article is broken; found VS2015 Build Tools [here](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

Installed that; 
Already have python2.7 installed which was required to install node on Win10

Ran
`npm config set python python2.7`

Finally.
`npm config set msvs_version 2015`

Failed with a different msbuild error, to be continued ...

`$ npm install --build-from-source --save sqlite3`

> sqlite3@4.0.4 install C:\Dev\OrangeAbacus\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build
`node-pre-gyp WARN Using request for node-pre-gyp https download
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Dev\OrangeAbacus\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Dev\\OrangeAbacus\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Dev\\OrangeAbacus\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\Dev\OrangeAbacus\node_modules\sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Dev\OrangeAbacus\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Dev\OrangeAbacus\node_modules\sqlite3\lib\binding\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Dev\OrangeAbacus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Dev\\OrangeAbacus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Dev\OrangeAbacus\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Dev\OrangeAbacus\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Dev\OrangeAbacus\node_modules\sqlite3\lib\binding\node-v64-win32-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\impli\AppData\Roaming\npm-cache\_logs\2018-11-23T21_37_35_150Z-debug.log`

**Comment by ddk632** [comment]
Checked `https://visualstudio.microsoft.com/vs/older-downloads/` for correct build tools, found it is the `Microsoft Build Tools 2015 Update 3`

Note: The `Microsoft Visual C++ 2015 Redistributable Update 3` doesn't seem to get (or properly install) the needed components on Win10;

As an aside, Attempting to the redistributable, logs pointed out that it cannot be installed when a newer version is installed (in this case, 2017); uninstalled 2017, and it worked; however, it only installed FileTracker folder, and none of the `Microsoft.Cpp.*` DLLs.

Thus the `Microsoft Build Tools 2015 Update 3` (`visualcppbuildtools_full.exe`) from this [link](https://go.microsoft.com/fwlink/?LinkId=615460) installed the full suite of `Microsoft.Cpp.*` DLLs

Ran `$ npm install --build-from-source --save sqlite3` and this time, SUCCESS!

**Comment by ddk632** [comment]
Duh! So sqlite shell doesn't get built here since sqllite3 is build directly into the app; downloading `https://www.sqlite.org/2018/sqlite-tools-win32-x86-3250300.zip` for the shell, although this won't really be needed, but I like to use the shell to verify data and be able to play with it outside of the programmatic environment.

**Comment by ddk632** [comment]
![image](https://user-images.githubusercontent.com/13021651/48972724-df300d00-effe-11e8-8af1-c11eaca61348.png)

**Comment by ddk632** [comment]
https://www.sqlite.org/cli.html
